#!/usr/bin/env python3

import sys
import os.path

def readlines(data):
    for line in data:
        sanitized_data=line.strip()
        input_list=sanitized_data.split()
        deduped = list(set(input_list))
        print(' '.join(deduped))


if not sys.stdin.isatty():
    readlines(sys.stdin.readlines())


if len(sys.argv) == 2:
    list_arguments = sys.argv
    list_arguments.pop(0)
    input_file = ' '.join(list_arguments)
    if os.path.exists(input_file):
        with open(input_file) as f:
            readlines(f.readlines())


elif len(sys.argv) > 1:
    list_arguments = sys.argv
    list_arguments.pop(0)
    deduped = list(set(list_arguments))
    print(' '.join(deduped))

