#!/usr/bin/env bash

set -e

if [[ -n "$1" ]]
then
    VALUE=$1
else
    VALUE=$(cat)    
fi

if [[ -z $VALUE ]]
then
    echo "You must specifiy some value"
    exit 1
fi

printf '%s\n' "$VALUE" | awk '{ print toupper($0) }'