#!/usr/bin/env python3

import os
import requests
import json
import pathlib
from pygments import highlight, lexers, formatters
from dotenv import load_dotenv

bin_symlink=pathlib.Path('/usr/bin/wip').resolve()
bin_realpath=os.path.dirname(bin_symlink)
env_file=os.path.join(bin_realpath, '.env')

load_dotenv(env_file)

def get_ip(url, token):
    url_request=''.join([url,token])
    r = requests.get(url_request)
    json_data = json.loads(r.content)
    formatted_json=json.dumps(json_data, indent=4)
    colorful_json=highlight(formatted_json, lexers.JsonLexer(), formatters.TerminalFormatter())
    print(colorful_json)


WIP_IPINFO_TOKEN=os.getenv('WIP_IPINFO_TOKEN')
WIP_IPGEOLOCATION_TOKEN=os.getenv('WIP_IPGEOLOCATION_TOKEN')


if WIP_IPGEOLOCATION_TOKEN is not None:
    get_ip('https://api.ipgeolocation.io/ipgeo?apiKey=', WIP_IPGEOLOCATION_TOKEN)

if WIP_IPINFO_TOKEN is not None:
    get_ip('https://ipinfo.io?token=', WIP_IPINFO_TOKEN)