#!/usr/bin/env bash

set -e

if [[ -n "$1" ]]
then
    VALUE=$1
else
    VALUE=$(cat)    
fi

if [[ -z $VALUE ]]
then
    echo "You must specifiy some value"
    exit 1
fi

echo "$VALUE" | sed -r 's/ ([a-z])/\U\1/gi' | sed -r 's/^([A-Z])/\l\1/'
